// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cakcuhuqsanuuyndaheu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNha2N1aHVxc2FudXV5bmRhaGV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNzc1MDYsImV4cCI6MjA1NDk1MzUwNn0.ONCWV6lk5VBr0eXbVNJBArLFv9IpFloAces3uLNq8sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);